### YamlMime:UniversalReference
items:
  - uid: '@fluentui/merge-styles!ICSPSettings:interface'
    summary: CSP settings for the stylesheet
    name: ICSPSettings
    fullName: ICSPSettings
    langs:
      - typeScript
    type: interface
    package: '@fluentui/merge-styles!'
    children:
      - '@fluentui/merge-styles!ICSPSettings#nonce:member'
  - uid: '@fluentui/merge-styles!ICSPSettings#nonce:member'
    summary: Nonce to inject into script tag
    name: nonce
    fullName: nonce
    langs:
      - typeScript
    type: property
    syntax:
      content: 'nonce?: string;'
      return:
        type:
          - string
