### YamlMime:TSType
name: ICSPSettings
uid: '@fluentui/merge-styles!ICSPSettings:interface'
package: '@fluentui/merge-styles!'
fullName: ICSPSettings
summary: CSP settings for the stylesheet
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: nonce
    uid: '@fluentui/merge-styles!ICSPSettings#nonce:member'
    package: '@fluentui/merge-styles!'
    fullName: nonce
    summary: Nonce to inject into script tag
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'nonce?: string;'
      return:
        type: string
