### YamlMime:TSType
name: IStyleSheetConfig
uid: '@fluentui/merge-styles!IStyleSheetConfig:interface'
package: '@fluentui/merge-styles!'
fullName: IStyleSheetConfig
summary: Stylesheet config.
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: classNameCache
    uid: '@fluentui/merge-styles!IStyleSheetConfig#classNameCache:member'
    package: '@fluentui/merge-styles!'
    fullName: classNameCache
    summary: >-
      Initial value for classnames cache. Key is serialized css rules associated
      with a classname.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: |-
        classNameCache?: {
                [key: string]: string;
            };
      return:
        type: |-
          {
                  [key: string]: string;
              }
  - name: cspSettings
    uid: '@fluentui/merge-styles!IStyleSheetConfig#cspSettings:member'
    package: '@fluentui/merge-styles!'
    fullName: cspSettings
    summary: CSP settings
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'cspSettings?: ICSPSettings;'
      return:
        type: '<xref uid="@fluentui/merge-styles!ICSPSettings:interface" />'
  - name: defaultPrefix
    uid: '@fluentui/merge-styles!IStyleSheetConfig#defaultPrefix:member'
    package: '@fluentui/merge-styles!'
    fullName: defaultPrefix
    summary: Default 'displayName' to use for a className.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'defaultPrefix?: string;'
      return:
        type: string
  - name: injectionMode
    uid: '@fluentui/merge-styles!IStyleSheetConfig#injectionMode:member'
    package: '@fluentui/merge-styles!'
    fullName: injectionMode
    summary: Injection mode for how rules are inserted.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'injectionMode?: InjectionMode;'
      return:
        type: InjectionMode
  - name: namespace
    uid: '@fluentui/merge-styles!IStyleSheetConfig#namespace:member'
    package: '@fluentui/merge-styles!'
    fullName: namespace
    summary: Default 'namespace' to attach before the className.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'namespace?: string;'
      return:
        type: string
  - name: onInsertRule
    uid: '@fluentui/merge-styles!IStyleSheetConfig#onInsertRule:member'
    package: '@fluentui/merge-styles!'
    fullName: onInsertRule
    summary: Callback executed when a rule is inserted.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'onInsertRule?: (rule: string) => void;'
      return:
        type: '(rule: string) =&gt; void'
  - name: rtl
    uid: '@fluentui/merge-styles!IStyleSheetConfig#rtl:member'
    package: '@fluentui/merge-styles!'
    fullName: rtl
    summary: >-
      Defines the default direction of rules for auto-rtlifying things. While
      typically this is represented as a DIR attribute in the markup, the DIR is
      not enough to control whether padding goes on the left or right. Use this
      to set the default direction when rules are registered.
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'rtl?: boolean;'
      return:
        type: boolean
