### YamlMime:UniversalReference
items:
  - uid: '@fluentui/react-internal!IKeytipConfigMap:interface'
    name: IKeytipConfigMap
    fullName: IKeytipConfigMap
    langs:
      - typeScript
    type: interface
    package: '@fluentui/react-internal!'
