### YamlMime:UniversalReference
items:
  - uid: '@fluentui/react-internal!IKeytipConfig:interface'
    name: IKeytipConfig
    fullName: IKeytipConfig
    langs:
      - typeScript
    type: interface
    package: '@fluentui/react-internal!'
    children:
      - '@fluentui/react-internal!IKeytipConfig#keytips:member'
  - uid: '@fluentui/react-internal!IKeytipConfig#keytips:member'
    name: keytips
    fullName: keytips
    langs:
      - typeScript
    type: property
    syntax:
      content: 'keytips: IKeytipConfigItem[];'
      return:
        type:
          - 'IKeytipConfigItem[]'
