### YamlMime:TSType
name: IKeytipConfig
uid: '@fluentui/react-internal!IKeytipConfig:interface'
package: '@fluentui/react-internal!'
fullName: IKeytipConfig
summary: ''
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: keytips
    uid: '@fluentui/react-internal!IKeytipConfig#keytips:member'
    package: '@fluentui/react-internal!'
    fullName: keytips
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'keytips: IKeytipConfigItem[];'
      return:
        type: 'IKeytipConfigItem[]'
