### YamlMime:UniversalReference
items:
  - uid: '@fluentui/react-compose!'
    name: '@fluentui/react-compose'
    fullName: '@fluentui/react-compose'
    langs:
      - typeScript
    type: package
    children:
      - '@fluentui/react-compose!ComponentWithAs:interface'
      - '@fluentui/react-compose!compose:function(1)'
      - '@fluentui/react-compose!ShorthandConfig:interface'
  - uid: '@fluentui/react-compose!compose:function(1)'
    name: 'compose(input, inputOptions)'
    fullName: 'compose(input, inputOptions)'
    langs:
      - typeScript
    type: function
    syntax:
      content: >-
        declare function compose<TElementType extends React.ElementType, TInputProps, TInputStylesProps, TParentProps,
        TParentStylesProps>(input: Input<TElementType, TInputProps>, inputOptions?: ComposeOptions<TInputProps,
        TInputStylesProps, TParentProps, TParentStylesProps>): ComponentWithAs<TElementType, TInputProps &
        TParentProps>;
      return:
        type:
          - 'ComponentWithAs<TElementType, TInputProps & TParentProps>'
        description: ''
      parameters:
        - id: input
          description: ''
          type:
            - 'Input<TElementType, TInputProps>'
        - id: inputOptions
          description: ''
          type:
            - 'ComposeOptions<TInputProps, TInputStylesProps, TParentProps, TParentStylesProps>'
      typeParameters:
        - id: TElementType
          type:
            - React.ElementType
        - id: TInputProps
        - id: TInputStylesProps
        - id: TParentProps
        - id: TParentStylesProps
references:
  - uid: '@fluentui/react-compose!ComponentWithAs:interface'
    name: ComponentWithAs
  - uid: '@fluentui/react-compose!ShorthandConfig:interface'
    name: ShorthandConfig
