### YamlMime:UniversalReference
items:
  - uid: 'office-ui-fabric-react!IKeytipConfig:interface'
    name: IKeytipConfig
    fullName: IKeytipConfig
    langs:
      - typeScript
    type: interface
    package: office-ui-fabric-react!
    children:
      - 'office-ui-fabric-react!IKeytipConfig#keytips:member'
  - uid: 'office-ui-fabric-react!IKeytipConfig#keytips:member'
    name: keytips
    fullName: keytips
    langs:
      - typeScript
    type: property
    syntax:
      content: 'keytips: IKeytipConfigItem[];'
      return:
        type:
          - 'IKeytipConfigItem[]'
