### YamlMime:TSType
name: IKeytipConfig
uid: 'office-ui-fabric-react!IKeytipConfig:interface'
package: office-ui-fabric-react!
fullName: IKeytipConfig
summary: ''
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: keytips
    uid: 'office-ui-fabric-react!IKeytipConfig#keytips:member'
    package: office-ui-fabric-react!
    fullName: keytips
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'keytips: IKeytipConfigItem[];'
      return:
        type: 'IKeytipConfigItem[]'
