### YamlMime:UniversalReference
items:
  - uid: '@fluentui/react-compose!ShorthandConfig:interface'
    name: ShorthandConfig
    fullName: ShorthandConfig
    langs:
      - typeScript
    type: interface
    syntax:
      typeParameters:
        - id: TProps
    package: '@fluentui/react-compose!'
    children:
      - '@fluentui/react-compose!ShorthandConfig#allowsJSX:member'
      - '@fluentui/react-compose!ShorthandConfig#mappedArrayProp:member'
      - '@fluentui/react-compose!ShorthandConfig#mappedProp:member'
  - uid: '@fluentui/react-compose!ShorthandConfig#allowsJSX:member'
    name: allowsJSX
    fullName: allowsJSX
    langs:
      - typeScript
    type: property
    syntax:
      content: 'allowsJSX?: boolean;'
      return:
        type:
          - boolean
  - uid: '@fluentui/react-compose!ShorthandConfig#mappedArrayProp:member'
    name: mappedArrayProp
    fullName: mappedArrayProp
    langs:
      - typeScript
    type: property
    syntax:
      content: 'mappedArrayProp?: keyof TProps;'
      return:
        type:
          - keyof TProps
  - uid: '@fluentui/react-compose!ShorthandConfig#mappedProp:member'
    name: mappedProp
    fullName: mappedProp
    langs:
      - typeScript
    type: property
    syntax:
      content: 'mappedProp?: keyof TProps;'
      return:
        type:
          - keyof TProps
