### YamlMime:TSType
name: ShorthandConfig
uid: '@fluentui/react-compose!ShorthandConfig:interface'
package: '@fluentui/react-compose!'
fullName: ShorthandConfig
summary: ''
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: allowsJSX
    uid: '@fluentui/react-compose!ShorthandConfig#allowsJSX:member'
    package: '@fluentui/react-compose!'
    fullName: allowsJSX
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'allowsJSX?: boolean;'
      return:
        type: boolean
  - name: mappedArrayProp
    uid: '@fluentui/react-compose!ShorthandConfig#mappedArrayProp:member'
    package: '@fluentui/react-compose!'
    fullName: mappedArrayProp
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'mappedArrayProp?: keyof TProps;'
      return:
        type: keyof TProps
  - name: mappedProp
    uid: '@fluentui/react-compose!ShorthandConfig#mappedProp:member'
    package: '@fluentui/react-compose!'
    fullName: mappedProp
    summary: ''
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'mappedProp?: keyof TProps;'
      return:
        type: keyof TProps
