### YamlMime:TSType
name: IKeytipConfigItem
uid: '@fluentui/react!IKeytipConfigItem:interface'
package: '@fluentui/react!'
fullName: IKeytipConfigItem
summary: ''
remarks: ''
isPreview: false
isDeprecated: false
type: interface
properties:
  - name: children
    uid: '@fluentui/react!IKeytipConfigItem#children:member'
    package: '@fluentui/react!'
    fullName: children
    summary: Children keytips of this keytip
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'children?: IKeytipConfigItem[];'
      return:
        type: 'IKeytipConfigItem[]'
  - name: content
    uid: '@fluentui/react!IKeytipConfigItem#content:member'
    package: '@fluentui/react!'
    fullName: content
    summary: Content for the keytip
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'content: string;'
      return:
        type: string
  - name: id
    uid: '@fluentui/react!IKeytipConfigItem#id:member'
    package: '@fluentui/react!'
    fullName: id
    summary: 'Identifier for the keytip, to be used to access in the configMap'
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'id: string;'
      return:
        type: string
  - name: optionalProps
    uid: '@fluentui/react!IKeytipConfigItem#optionalProps:member'
    package: '@fluentui/react!'
    fullName: optionalProps
    summary: Optional props in IKeytipProps
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'optionalProps?: Partial<IKeytipProps>;'
      return:
        type: Partial&lt;IKeytipProps&gt;
  - name: sequence
    uid: '@fluentui/react!IKeytipConfigItem#sequence:member'
    package: '@fluentui/react!'
    fullName: sequence
    summary: >-
      Key Sequence for this keytip only If sequence is not defined it will be
      derived from the content string
    remarks: ''
    isPreview: false
    isDeprecated: false
    syntax:
      content: 'sequence?: string;'
      return:
        type: string
